name: misalign
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.16
  - h5py=3.9.0
  - hdf5=1.14.1
  - hydra-core=1.3.2
  - lightning=2.0.1
  - monai=1.2.0
  - pip=23.1.2
  - pytorch-cuda=11.8
  - torchvision
  - rich=13.4.2
  - torchmetrics=0.11.4
  - tqdm=4.65.0
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - matplotlib
  - gdown
  - pip:
    - colorlog==6.7.0
    - hydra-colorlog==1.2.0
    - lpips==0.1.4
    - scipy==1.11.1
    - torch-fidelity==0.3.0
    - torchmetrics[image]==0.11.4
    - nibabel>=5.*
    - pyrootutils==1.0.4
    - pytest
    - scikit-learn
    - higher # newly added
    - lpips # newly added




