_target_: misalign.models.dam_module.DAMModule

name: dam

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  betas: [0.5, 0.999]
  weight_decay: 0.0001

netG_A:
  _target_: misalign.models.components.networks_dam.define_G
  input_nc: 1
  output_nc: 1
  feat_ch: 64
  netG: 'dam'
  demodulate: true
  requires_grad: true

netG_B:
  _target_: misalign.models.components.networks_dam.define_G
  input_nc: 1
  output_nc: 1
  feat_ch: 64
  netG: 'dam'
  demodulate: true
  requires_grad: true

params: # Other params
  lambda_style: 1
  lambda_cycle_a: 1
  lambda_cycle_b: 1
  lambda_sc: 0.1