_target_: misalign.models.gcgan_module.GCCycleGANModule

name: gcgan

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  betas: [0.5, 0.999]
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 10

netG_A:
  _target_: misalign.models.components.networks.define_G
  input_nc: 1
  output_nc: 1
  ngf: 64
  norm: 'instance'
  use_dropout: False
  init_type: 'normal'

netG_B:
  _target_: misalign.models.components.networks.define_G
  input_nc: 1
  output_nc: 1
  ngf: 64
  norm: 'instance'
  use_dropout: False
  init_type: 'normal'

netD_A:
  _target_: misalign.models.components.networks.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal'
  
netD_B:
  _target_: misalign.models.components.networks.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal'
  
params: # Other params
  pool_size: 0
  lambda_cycle: 100
  lambda_identity: 0
  lambda_gc: 1
