_target_: misalign.models.pgan_module.PixelGANModule

name: pgan

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  betas: [0.5, 0.999]
  weight_decay: 0.0001

netG_A:
  _target_: misalign.models.components.networks.define_G
  input_nc: 1
  output_nc: 1
  ngf: 64
  norm: 'instance'
  use_dropout: False
  init_type: 'normal'

netG_B:
  _target_: misalign.models.components.networks.define_G
  input_nc: 1
  output_nc: 1
  ngf: 64
  norm: 'instance'
  use_dropout: False
  init_type: 'normal'

netD_A:
  _target_: misalign.models.components.networks.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal'

netD_B:
  _target_: misalign.models.components.networks.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal'

params: # Other params
  pool_size: 0
  lambda_l1: 20
  lambda_vgg: 20
  flag_meta_learning: False
  dir_meta_learning: ${paths.root_dir}/data/IXI/val/prepared_data_0.0_0.0_0.0_0.0_0.0.h5
  reverse: ${data.reverse}
  flag_register: False # proposed에선 True
  flag_meta_use_spatial: True
  flag_use_mask: False
  meta_type: LRE
